[#25] Создание филиалов
kzagorulko/flower-system pull request #35
Opened 2020-11-11 17:37 UTC by mik0war

- созданы модели Branch и User_x_Branch
- созданы методы GET, POST и PATCH
- изменены методы user'a в соответствии с задачей

2020-11-11 18:22 UTC, kzagorulko reviewed
Мне очень нравится, что ты успешно включился в работу, но косяки есть

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/branches/models.py
> +                          db.ForeignKey('branches.id'), nullable=False)
лучше перенести так:
```python
branch_id = db.Column(
    db.Integer,db.ForeignKey('branches.id'), nullable=False
)
```

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/branches/resources.py
> +            )
в юзерах устаревшая конструкция, с фронта приходит поля поиска и надо сделать как в поставщиках:
```python
        if 'name' in query_params:
            providers_query = providers_query.where(
                ProviderModel.name.ilike(f'%{query_params["name"]}%')
            )
            total_query = total_query.where(
                ProviderModel.name.ilike(f'%{query_params["name"]}%')
            )
```

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/branches/resources.py
> +            branches_query = branches_query.\
символа `\` стоит избегать и использовать перенос по скобочке:

```python
branches_query.limit(
    per_page
).offset(page * per_page)
```

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/branches/resources.py
> +        return make_error(description='Branch not found', status_code=404)
мы обсуждали, что нужно сделать отображение пользователей привязаных к филиалу и action здесь 'get_one'
![image](https://user-images.githubusercontent.com/31614542/98848074-3769af00-2462-11eb-9f65-83a86e2e10f0.png)

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/branches/resources.py
> +
добавь здесь `if values:` как в юзерах

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/resources.py
> +        users_query = UserModel.outerjoin(RoleModel)\
здесь тоже перенос по скобкам

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/resources.py
> +
по филиалу не надо фильтровать, нет такой возможности

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/resources.py
> +        users_query = UserModel.outerjoin(RoleModel)\
да и не нужно тут это делать, когда получается список адреса филиалов не показываются

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/resources.py
> +                role=RoleModel, branch=UserBranchModel
отсюда тоже надо убрать branch

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/resources.py
> +
А причём тут `RoleNotExist`?

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/utils.py
> +        await UserBranchModel.delete\
`\`

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/utils.py
> +                  (UserBranchModel.branch_id in branches))
это условие удалит всё, что не принадлежит пользователю и не в списке, не надо так
 ```python
((UserBranchModel.user_id == user_id) & ~(UserBranchModel.branch_id in branches))
```

2020-11-11 18:22 UTC, kzagorulko commented on backend/flower/core/users/utils.py
> +            await insert(UserBranchModel)\
`\`

2020-11-11 18:22 UTC, kzagorulko commented on backend/migrations/versions/b1a0d6cd7fa7_.py
> -"""empty message
👀

2020-11-11 18:29 UTC, DeuteriumQ requested changes

2020-11-11 18:29 UTC, DeuteriumQ commented on backend/flower/core/branches/resources.py
> +                BranchModel.display_name.ilike(f'%{query_params["search"]}%')
это не будет работать по двум причинам:
1) ты забыл поменять display_name на address
2) вместо search React Admin будет вставлять имя поля, по которому поиск (в данном случае 'address'

2020-11-11 18:29 UTC, DeuteriumQ commented on backend/flower/core/branches/models.py
> +    def jsonify(self, for_card=False):
Зачем тут for_card, если он не используется?

2020-11-11 18:29 UTC, DeuteriumQ commented on backend/flower/core/branches/resources.py
> +    Route('/{branch_id:int}', Branch),
Нужно добавить рут с экшенсами для ресурса
('/actions', get_actions, methods=['GET'])

```python
@jwt_required
async def get_actions(request, user):
    return JSONResponse(await permissions.get_actions(user.role_id))
```

2020-11-11 18:29 UTC, DeuteriumQ commented on backend/migrations/versions/b1a0d6cd7fa7_.py
> -"""empty message
а куда делся

2020-11-11 18:34 UTC, mik0war commented on backend/flower/core/users/resources.py
> +
То есть это убрать?

2020-11-11 19:00 UTC, kzagorulko commented on backend/flower/core/users/resources.py
> +
да

2020-11-12 21:25 UTC, kzagorulko commented on backend/flower/core/users/utils.py
> +                  (UserBranchModel.branch_id in branches))
советчик блять
```python
((UserBranchModel.user_id == user_id) & ~(UserBranchModel.branch_id.in_(branches)))
```

2020-11-12 21:55 UTC, DeuteriumQ approved these changes
🥇

2020-11-12 22:29 UTC, Ivan753 approved these changes

2020-11-12 22:50 UTC, merged