[#26] Создание продуктов и продаж
kzagorulko/flower-system pull request #36
Opened 2020-11-14 15:35 UTC by Ivan753

- настроена работа с продуктами
  - созданы модель `ProductModel`
  - созданы роуты `POST`, `GET` (все и один), `PATCH`
  - разработан `MediaUtils` для сохранения/удаления файла: из `base64`; из `form-data`
  - на стороне `Frontend`
    - настроена отправка изображения в `base64` с помощью pipeline `prepareImage`
    - созданы `ProductCreate`, `ProductEdit`, `ProductList`
- разработаны отчеты о продажах
  - создана модель `Sales`
  - созданы роуты `POST`, `GET` (все и один) -- в соответствии с issud #26 
- произведен рефактор `Backend`
  - создан `GinoQueryHelper` с методами `pagination` и `order` для унификации механизма пагинации и сортировки запроса в роутах
  - определены возможные действия для `Permissions` в `PermissionActions` (доступно из `Permissions`)

closes #26

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/products/models.py
> +        }
если потом переделывать на нжинкс, будут проблемы, нужна отдельная константа

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/products/resources.py
> +        except Exception as e:
рэйзить прямо в трае не надо, если используешь ифы – то просто там выкидывай ошибки или вынеси проверки в отдельную функцию

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/products/utils.py
> +    @staticmethod
вынеси лучше MediaUtils из продуктов в просто utils

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/models.py
> +                          db.ForeignKey('branches.id'), nullable=True)
перенёс бы после скобочки, а не после запятой

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/models.py
> +            result['branch'] = self._branch.jsonify()
Сделал проперти product и branch, чтобы забирать дату из _branch и _product

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/resources.py
> +permissions = Permissions(app_name='products')
действительно products

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/resources.py
> +                    user, ['admin', 'sales_department']
у нас sales_departament не может создавать отчёты

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/resources.py
> +                (SalesModel.date_year == float(query_params['year'])))
у нас такой фильтрации

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/resources.py
> +        })
надо бы и  total  отдавать

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/resources.py
> +        sale_id = int(request.path_params['sale_id'])
указал в пути, что sale_id – это int и ещё раз. привёл, Ванёк блин

2020-11-14 16:10 UTC, kzagorulko commented on backend/flower/core/sales/utils.py
> +class MediaUtils:
ну теперь в каждых ютилсах по медиаютилсам

2020-11-14 16:11 UTC, DeuteriumQ commented on backend/flower/core/sales/resources.py
> +permissions = Permissions(app_name='products')
))

2020-11-14 16:27 UTC, DeuteriumQ requested changes

2020-11-14 16:27 UTC, DeuteriumQ commented on frontend/src/App.js
> +        ) : null,
А где sales

2020-11-14 16:27 UTC, DeuteriumQ commented on frontend/src/api/dataProvider.js
> +  // TODO: fix
DO NOW: fix

2020-11-14 16:27 UTC, DeuteriumQ commented on frontend/src/components/ProductsList/index.js
> +        <TextInput disabled={!permissions.actions.includes('update')} source="description" multiline />
Зачем ты добавил тут проверку разрешений в каждое поле, если уже есть проверка в скоупе Админа, и этого компонента не будет, если не будет разрешений.
:exclamation: Убрать

2020-11-14 16:27 UTC, DeuteriumQ commented on frontend/src/components/ProductsList/index.js
> +      <ImageField source="image_path" title="image" />
добавить проп sortable={false}

2020-11-14 16:31 UTC, DeuteriumQ commented on backend/flower/core/products/resources.py
> +        if 'search' in query_params:
не 'search', а 'name', потому что поиск по name, объяснял Антону

2020-11-14 16:34 UTC, Ivan753 commented on backend/flower/core/products/resources.py
> +        except Exception as e:
Немного притянуто с валидацией, но в общем это нормальная практика; Исключение может быть получено из вложенных методом; например, метода сохранения файлов

2020-11-14 16:35 UTC, DeuteriumQ commented on frontend/src/components/ProductsList/index.js
> +        <TextInput disabled={!permissions.actions.includes('update')} source="description" multiline />
В списке провайдеров это проверяется, потому что есть update и update_status для разных действий и для разных людей.
Тут одно и то же действие, которое уже проверяется в корне приложения

2020-11-14 16:36 UTC, Ivan753 commented on backend/flower/core/products/models.py
> +        }
Будем смотреть по надобности

2020-11-14 16:49 UTC, Ivan753 commented on backend/flower/core/sales/models.py
> +            result['branch'] = self._branch.jsonify()
Опиши, в чем проблема

2020-11-14 16:50 UTC, Ivan753 commented on backend/flower/core/sales/resources.py
> +                (SalesModel.date_year == float(query_params['year'])))
Будет предусмотрена на случай, если успеем реализовать на стороне `frontend`

2020-11-14 16:55 UTC, DeuteriumQ commented on backend/flower/core/sales/resources.py
> +                (SalesModel.date_year == float(query_params['year'])))
Там можно добавлять фильтры за пять сек
![filters](https://sun9-69.userapi.com/IrPon1bKPPqwoHu0RCmRa2j__u7HzJOM7SM5cQ/0mTk3J8jfyg.jpg)

2020-11-14 20:26 UTC, DeuteriumQ commented on frontend/src/components/ProductsList/index.js
> +  const { loaded } = usePermissions('/products');
вообще убери использование хука - просто компонент

2020-11-15 09:41 UTC, DeuteriumQ approved these changes

2020-11-15 15:15 UTC, kzagorulko commented on backend/flower/core/products/resources.py
> +        except Exception as e:
вынеси в отдельную функцию в таком случае или удали

2020-11-15 17:51 UTC, kzagorulko commented on backend/flower/core/products/resources.py
> +            )
```python
current_query = current_query.where(...)
```

2020-11-15 17:51 UTC, kzagorulko commented on backend/flower/core/utils.py
> +    )
```python
.gino.first()
```

2020-11-15 17:51 UTC, kzagorulko commented on backend/migrations/versions/2c5aac614e6f_.py
> +    )
ну и зачем такой пример с изображениями `none1`?

2020-11-15 17:51 UTC, kzagorulko commented on backend/requirements.txt
> +aiofiles==0.6.0
это используется?

2020-11-15 17:51 UTC, kzagorulko commented on frontend/src/App.js
> +        ) : null,
![image](https://user-images.githubusercontent.com/31614542/99192511-48792f80-2784-11eb-9ae7-ce6fb9a37f47.png)

2020-11-16 14:01 UTC, kzagorulko approved these changes

2020-11-16 14:03 UTC, merged